#define application name
spring:
   application:
       name: employee-search-service

#define server port and contextPath
server:
   port: 8080
   servlet:
      context-path: /employee-search-service
